spring:
  application:
    name: shaLotoPro
  cloud:
    config:
      profile: shaLoto
      label: 1
      uri: http://localhost:8888
    
  
  profiles: 
    active: dev
  
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
  domain:
    datasource:
      url: jdbc:postgresql://127.0.0.1:5432/sha_test
      username: postgres
      password: postgre
      driverClassName: org.postgresql.Driver
  loto:
    datasource:
      url: jdbc:postgresql://127.0.0.1:5432/sha_test2
      username: postgres
      password: postgre
      driverClassName: org.postgresql.Driver
      
  session:
    store-type: none

  redis:
    host: 127.0.0.1
    port: 6379
    
api-service:
  name: shaLoto

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    sha.work.mapper.loto: DEBUG
  file: logs/logback-demo.log
  path: logs
  
server:
  port: 8092
  
mybatis:
  configuration:
    map-underscore-to-camel-case: true 

#### CRON ####
# 秒/分/時/日/月/曜日
cron:
  #LOTO7 毎週土曜日のAM 00:00に実行（金抽）
  loto7Cron: 0 0 0 * * 6
  #LOTO6 毎週火、金曜日のAM 00:00に実行（月、木抽）
  loto6Cron: 0 0 0 * * 2,5
  #LOTO6 毎週水曜日のAM 00:00に実行（火抽）
  miniLotoCron: 0 0 0 * * 3
################

#### no env##### 
#cloud.aws:
#  credentials:
#    accessKey: aws_access_key
#    secretKey: aws_secret_access_key
#  region:
#    static: ap-northeast-1 
################